services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: hiddify_bot
      MYSQL_USER: hiddify_user
      MYSQL_PASSWORD: 54asd54sa23
      MYSQL_ROOT_PASSWORD: root_password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - hiddify_mysql_data:/var/lib/mysql

  app:
    image: mhsenpc/hiddify_bot:latest
    restart: always
    ports:
      - "8888:8080"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: hiddify_bot
      DATABASE_USERNAME: hiddify_user
      DATABASE_PASSWORD: 54asd54sa23
    depends_on:
      - mysql
    volumes:
      - ./storage:/app/storage

volumes:
  hiddify_mysql_data: