package com.mhsenpc.hiddifybot.bot.enums;

public enum UserStep {
    ADMIN_SELECT_PLAN,
    ADMIN_VIEW_USERS,
    ADMIN_VIEW_PLANS,
    ADMIN_WAITING_FOR_PLAN_COMMANDS,
    ADMIN_CREATE_PLAN_WAIT_FOR_MONTH,
    ADMIN_CREATE_PLAN_WAIT_FOR_TRAFFIC,
}
